### PR TITLE
Build with no_std

### PR DESCRIPTION
**Pull request by g2p**

### CODE REVIEW

**Comment by sfackler** [comment]
All of simd's standard library dependencies (`mem` and `ops`) are in libcore - I think this library can just become unconditionally `#[no_std`].

**Comment by g2p** [comment]
I've made it unconditional.

**Comment by BurntSushi** [comment]
This seems OK to me. I can't think of a specific reason why this crate would ever need `std` specifically.

It looks like CI might be failing because of the examples, which I think need to be cleaned up before merging this PR.

**Comment by g2p** [comment]
See https://github.com/rust-lang-nursery/simd/pull/15 for examples cleanups.

**Comment by BurntSushi** [comment]
@g2p Could you rebase this on current master and force push? That should get CI going again.

**Comment by g2p** [comment]
Rebased.

**Comment by BurntSushi** [comment]
Thanks!

**Pull request merged**
